server.port=9092
spring.application.name=spring-boot-ai-mcp-client

logging.level.io.modelcontextprotocol.client=DEBUG
logging.level.io.modelcontextprotocol.spec=DEBUG
logging.pattern.console=

mcp.server.jar-path=C:/Users/t123445/spring-boot-ai-mongo-mcp-server-main/target/spring-boot-ai-mongo-mcp-server-0.0.2-SNAPSHOT.jar
mcp.server.port=8080
mcp.server.host=localhost
